# Generated by Django 6.0.7 on 2026-08-25 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('township', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(default='MMR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_organization_address',
                'ordering': ['city', 'township', 'address_line_1'],
            },
        ),
        migrations.AlterModelOptions(
            name='branchprofile',
            options={'ordering': ['branch_code']},
        ),
        migrations.RemoveField(
            model_name='branchprofile',
            name='branch_manager_id',
        ),
        migrations.RemoveField(
            model_name='branchprofile',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='branchprofile',
            name='zone_code',
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='branchprofile',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_profiles', to='erp_organization.legalentityprofile'),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_departments', to='erp_organization.branchprofile'),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_profiles', to='erp_organization.legalentityprofile'),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_department_profiles', to='erp_organization.departmentprofile'),
        ),
        migrations.AlterField(
            model_name='physicallocationprofile',
            name='responsible_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_locations', to='erp_organization.branchprofile'),
        ),
        migrations.AlterField(
            model_name='physicallocationprofile',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_locations', to='erp_organization.departmentprofile'),
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='erp_organization.address'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('region_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_organization_region',
                'ordering': ['region_name'],
                'indexes': [models.Index(fields=['region_code'], name='erp_organiz_region__83091e_idx'), models.Index(fields=['is_active'], name='erp_organiz_is_acti_fd8200_idx')],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='erp_organization.region'),
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='erp_organization.region'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(db_index=True, max_length=20)),
                ('zone_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='erp_organization.region')),
            ],
            options={
                'db_table': 'erp_organization_zone',
                'ordering': ['zone_name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='erp_organization.zone'),
        ),
        migrations.AddField(
            model_name='branchprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='erp_organization.zone'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['branch_code'], name='erp_organiz_branch__9c26ad_idx'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['region'], name='erp_organiz_region__4d41f4_idx'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['zone'], name='erp_organiz_zone_id_04409d_idx'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['address'], name='erp_organiz_address_035a06_idx'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['legal_entity'], name='erp_organiz_legal_e_d26377_idx'),
        ),
        migrations.AddIndex(
            model_name='branchprofile',
            index=models.Index(fields=['is_active'], name='erp_organiz_is_acti_88dc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['zone_code'], name='erp_organiz_zone_co_e91b19_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['region'], name='erp_organiz_region__b23973_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active'], name='erp_organiz_is_acti_987a9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('region', 'zone_code'), name='unique_zone_code_per_region'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['region'], name='erp_organiz_region__f4cfda_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['zone'], name='erp_organiz_zone_id_8a949e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='erp_organiz_city_aaa23e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['township'], name='erp_organiz_townshi_ec08a0_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_active'], name='erp_organiz_is_acti_a8f9e8_idx'),
        ),
    ]
