# Generated by Django 6.0.7 on 2026-08-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_organization', '0002_address_alter_branchprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country_code',
        ),
        migrations.AddField(
            model_name='region',
            name='timezone_name',
            field=models.CharField(blank=True, db_index=True, default='Asia/Yangon', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='timezone_abbreviation',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='utc_offset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['timezone_name'], name='erp_organiz_timezon_c6f783_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['timezone_abbreviation'], name='erp_organiz_timezon_b61b6f_idx'),
        ),
    ]
