# Generated by Django 6.0.7 on 2026-08-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_organization', '0003_remove_address_country_code_region_timezone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='timezone_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
