# Generated by Django 5.2.2 on 2026-06-29 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('policy_code', models.CharField(max_length=100, unique=True)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'partner_business_policy',
                'ordering': ['policy_code'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRoleConflictRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('existing_role', models.CharField(max_length=100)),
                ('new_role', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('business_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_conflict_rules', to='erp_partners.businesspolicy')),
            ],
            options={
                'db_table': 'partner_role_conflict_rule',
                'unique_together': {('existing_role', 'new_role')},
            },
        ),
    ]
