# Generated by Django 6.0.6 on 2026-10-05 06:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_asset_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('draft_date', models.DateField()),
                ('entry_source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Excel/CSV Import'), ('WIP_TRANSFER', 'WIP Transfer')], default='MANUAL', max_length=30)),
                ('lifecycle_status', models.CharField(choices=[('DRAFT', 'Draft'), ('CAPITALIZED', 'Capitalized'), ('COMMISSIONED', 'Commissioned'), ('DECOMMISSIONED', 'Decommissioned'), ('DISPOSED', 'Disposed')], default='DRAFT', max_length=30)),
                ('validation_status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('WARNING', 'Warning'), ('DECOMMISSIONED', 'Decommissioned'), ('ERROR', 'Error')], default='INCOMPLETE', max_length=20)),
                ('capitalization_eligible', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PRINTED', 'Printed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_assets_updated', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_assets_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'far_asset_core',
                'ordering': ['-draft_date', '-id'],
                'permissions': [('view_far_assets', 'Can view FAR draft assets'), ('create_far_assets', 'Can create FAR draft assets'), ('update_far_assets', 'Can update FAR draft assets'), ('delete_far_assets', 'Can delete FAR draft assets'), ('validate_far_assets', 'Can validate FAR draft assets'), ('print_far_assets', 'Can print FAR approval documents'), ('capitalize_far_assets', 'Can capitalize FAR assets'), ('bulk_capitalize_far_assets', 'Can bulk capitalize FAR assets')],
            },
        ),
        migrations.CreateModel(
            name='AssetClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(max_length=150)),
                ('asset_category', models.CharField(max_length=150)),
                ('asset_subcategory', models.CharField(blank=True, max_length=150)),
                ('asset_group', models.CharField(blank=True, max_length=150)),
                ('depreciation_policy_group', models.CharField(blank=True, max_length=150)),
                ('useful_life', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('depreciation_method', models.CharField(blank=True, max_length=100)),
                ('capitalization_threshold_check', models.BooleanField(default=False)),
                ('tax_asset_category', models.CharField(blank=True, max_length=150)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_classification',
            },
        ),
        migrations.CreateModel(
            name='AssetBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=100)),
                ('component_flag', models.BooleanField(default=False)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='core_entity_django.assetcore')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_assets', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_basic_info',
            },
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('IMPORT', 'Import'), ('ERROR_CORRECTION', 'Error Correction'), ('WIP_TRANSFER', 'Wip Transfer'), ('PRINT', 'Print'), ('VALIDATE', 'Validate'), ('CAPITALIZE', 'Capitalize'), ('BULK_CAPITALIZE', 'Bulk Capitalize')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('DELIVERY_NOTE', 'Delivery Note'), ('APPROVAL', 'Approval'), ('WIP_COMPLETION', 'Wip Completion'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='far/assets/%Y/%m/')),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core_entity_django.assetcore')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'far_asset_document',
            },
        ),
        migrations.CreateModel(
            name='AssetFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('other_directly_attributable_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_capitalizable_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('functional_currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capitalization_date', models.DateField(blank=True, null=True)),
                ('gl_asset_account_id', models.UUIDField(blank=True, null=True)),
                ('accumulated_depreciation_account_id', models.UUIDField(blank=True, null=True)),
                ('depreciation_expense_account_id', models.UUIDField(blank=True, null=True)),
                ('cost_center_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=150)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_financial_info',
            },
        ),
        migrations.CreateModel(
            name='AssetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('template_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'far_asset_import_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('error_type', models.CharField(choices=[('WARNING', 'Warning'), ('BLOCKING', 'Blocking')], default='BLOCKING', max_length=20)),
                ('suggested_correction', models.TextField(blank=True)),
                ('corrected', models.BooleanField(default=False)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core_entity_django.assetimportbatch')),
            ],
            options={
                'db_table': 'far_asset_import_error',
            },
        ),
        migrations.CreateModel(
            name='AssetLocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_id', models.BigIntegerField()),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('building_floor_room', models.CharField(blank=True, max_length=255)),
                ('rack_space_area', models.CharField(blank=True, max_length=255)),
                ('current_physical_status', models.CharField(blank=True, max_length=100)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_location_info',
            },
        ),
        migrations.CreateModel(
            name='AssetResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department_id', models.BigIntegerField(blank=True, null=True)),
                ('custodian_partner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('asset_controller_partner_id', models.UUIDField(blank=True, null=True)),
                ('assigned_user_partner_id', models.UUIDField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility', to='core_entity_django.assetcore')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSupplierAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_partner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('procurement_method', models.CharField(blank=True, max_length=100)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('warranty_provider_partner_id', models.UUIDField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_info', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_supplier_acquisition',
            },
        ),
        migrations.CreateModel(
            name='AssetWipReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip_item_reference', models.CharField(max_length=150)),
                ('wip_project_reference', models.CharField(blank=True, max_length=150)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transfer_date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wip_reference', to='core_entity_django.assetcore')),
            ],
            options={
                'db_table': 'far_asset_wip_reference',
            },
        ),
        migrations.CreateModel(
            name='CapitalizationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitalization_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('gl_asset_account', models.CharField(max_length=100)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capitalization_transaction', to='core_entity_django.assetcore')),
                ('capitalized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_capitalizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'far_capitalization_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetcore',
            index=models.Index(fields=['lifecycle_status'], name='idx_far_asset_status'),
        ),
        migrations.AddIndex(
            model_name='assetcore',
            index=models.Index(fields=['validation_status'], name='idx_far_asset_validation'),
        ),
        migrations.AddIndex(
            model_name='assetcore',
            index=models.Index(fields=['entry_source'], name='idx_far_asset_source'),
        ),
        migrations.AddIndex(
            model_name='assetcore',
            index=models.Index(fields=['capitalization_eligible'], name='idx_far_asset_eligible'),
        ),
        migrations.AddIndex(
            model_name='assetcore',
            index=models.Index(fields=['is_deleted'], name='idx_far_asset_deleted'),
        ),
        migrations.AddIndex(
            model_name='assetclassification',
            index=models.Index(fields=['asset_class'], name='idx_far_class_class'),
        ),
        migrations.AddIndex(
            model_name='assetclassification',
            index=models.Index(fields=['asset_category'], name='idx_far_class_category'),
        ),
        migrations.AddIndex(
            model_name='assetbasicinfo',
            index=models.Index(fields=['asset_name'], name='idx_far_basic_name'),
        ),
        migrations.AddIndex(
            model_name='assetbasicinfo',
            index=models.Index(fields=['serial_number'], name='idx_far_basic_serial'),
        ),
        migrations.AddIndex(
            model_name='assetbasicinfo',
            index=models.Index(fields=['asset_type'], name='idx_far_basic_type'),
        ),
        migrations.AddIndex(
            model_name='assetauditlog',
            index=models.Index(fields=['asset', 'timestamp'], name='idx_far_audit_asset_time'),
        ),
        migrations.AddIndex(
            model_name='assetauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='idx_far_audit_action_time'),
        ),
        migrations.AddIndex(
            model_name='assetauditlog',
            index=models.Index(fields=['batch_number'], name='idx_far_audit_batch'),
        ),
        migrations.AddIndex(
            model_name='assetdocument',
            index=models.Index(fields=['asset', 'document_type'], name='idx_far_doc_asset_type'),
        ),
        migrations.AddIndex(
            model_name='assetimporterror',
            index=models.Index(fields=['batch', 'row_number'], name='idx_far_import_err_row'),
        ),
        migrations.AddIndex(
            model_name='assetlocationinfo',
            index=models.Index(fields=['legal_entity_id'], name='idx_far_loc_legal_entity'),
        ),
        migrations.AddIndex(
            model_name='assetlocationinfo',
            index=models.Index(fields=['branch_id'], name='idx_far_loc_branch'),
        ),
        migrations.AddIndex(
            model_name='assetlocationinfo',
            index=models.Index(fields=['department_id'], name='idx_far_loc_department'),
        ),
        migrations.AddIndex(
            model_name='assetlocationinfo',
            index=models.Index(fields=['location_id'], name='idx_far_loc_location'),
        ),
        migrations.AddIndex(
            model_name='assetsupplieracquisition',
            index=models.Index(fields=['supplier_partner_id'], name='idx_far_supplier_partner'),
        ),
        migrations.AddIndex(
            model_name='assetsupplieracquisition',
            index=models.Index(fields=['warranty_provider_partner_id'], name='idx_far_warranty_provider'),
        ),
        migrations.AddIndex(
            model_name='assetwipreference',
            index=models.Index(fields=['wip_item_reference'], name='idx_far_wip_item'),
        ),
        migrations.AddIndex(
            model_name='assetwipreference',
            index=models.Index(fields=['wip_project_reference'], name='idx_far_wip_project'),
        ),
        migrations.AddIndex(
            model_name='capitalizationtransaction',
            index=models.Index(fields=['capitalization_date'], name='idx_far_cap_date'),
        ),
    ]
