# Generated by Django 6.0.6 on 2026-10-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_entity_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfinancialinfo',
            name='funding_source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
